In [ ]:
import numpy as np

In [ ]:
list1 = np.array([1,2,5,7])
list2 = np.array([4,7,9,2])

result = list1 * list2
print(result)

[ 4 14 45 14]


## **Multidimensional Arrays in Python**

In [ ]:
from numpy import *

In [ ]:
array1 = array([
                [1,2,3,4,6,8],
                [8,4,3,6,2,1]
])

print(array1)

[[1 2 3 4 6 8]
 [8 4 3 6 2 1]]


In [ ]:
print(array1.dtype) # show data type

int64


In [ ]:
print(array1.ndim) # show dymanshon

2


In [ ]:
print(array1.shape) # show array shape

(2, 6)


In [ ]:
print(array1.size)

12


In [ ]:
array2 = array1.flatten() # 2 dymanshon to 1 dymanshon
print(array2)

[1 2 3 4 6 8 8 4 3 6 2 1]


In [ ]:
array3 = array2.reshape(2,6) # 1 dymonshon to 2 dymanshon
print(array3)

[[1 2 3 4 6 8]
 [8 4 3 6 2 1]]


In [ ]:
array4 = array2.reshape(2,2,3) # make 3 dymonshon array
print(array4) 

[[[1 2 3]
  [4 6 8]]

 [[8 4 3]
  [6 2 1]]]


In [ ]:
print(array4.ndim)

3


# **Matrix Multiplication**

In [ ]:
m1 = ([1,2,3],
      [4,5,6],
      [7,3,5]
      )

m2 = ([3,4,2],
      [7,8,9],
      [3,5,9]
      )

print(m1)
print(m2)

([1, 2, 3], [4, 5, 6], [7, 3, 5])
([3, 4, 2], [7, 8, 9], [3, 5, 9])


In [ ]:
m1 = ([1,2,3],
      [4,5,6],
      [7,3,5]
      )

m2 = ([3,4,2],
      [7,8,9],
      [3,5,9]
      )

result = np.add(m1,m2) # addition
print(result)

[[ 4  6  5]
 [11 13 15]
 [10  8 14]]


In [ ]:
m1 = ([1,2,3],
      [4,5,6],
      [7,3,5]
      )

m2 = ([3,4,2],
      [7,8,9],
      [3,5,9]
      )

result = np.subtract(m1,m2) # subtractshon
print(result)

[[-2 -2  1]
 [-3 -3 -3]
 [ 4 -2 -4]]


In [ ]:
m1 = ([1,2,3],
      [4,5,6],
      [7,3,5]
      )

m2 = ([3,4,2],
      [7,8,9],
      [3,5,9]
      )

result = np.multiply(m1,m2) # subtractshon
print(result)

[[ 3  8  6]
 [28 40 54]
 [21 15 45]]


In [ ]:
m1 = ([1,2,3],
      [4,5,6],
      [7,3,5]
      )

m2 = ([3,4,2],
      [7,8,9],
      [3,5,9]
      )
# 1*3 + 2*7 + 3*3 = 26
result = np.dot(m1,m2)
print(result)

[[ 26  35  47]
 [ 65  86 107]
 [ 57  77  86]]
