In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1,2,3,4]) # Make 1D array
print(arr_1d)

[1 2 3 4]


In [4]:
type(arr_1d)

numpy.ndarray

In [5]:
arr_1d.ndim # To Chack array dymanshon

1

In [6]:
arr_2d = np.array([  # Make 2D array
    [1,2,3,4],
    [5,6,7,8] 
    ])

print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr_2d.ndim # To Chack array dymanshon

2

In [8]:
arr_2d.size # Chack array size

8

In [9]:
arr_1d.size # Check array size

4

In [10]:
arr_2d.shape # row, colm

(2, 4)

In [11]:
arr_2d.dtype # Check data type

dtype('int32')

In [12]:
# Video 09 Done ----->

In [13]:
mx_1s = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
mx_1s = np.ones(5) # Dymanshon of colam
print(mx_1s)

[1. 1. 1. 1. 1.]


In [15]:
mx_1s.dtype

dtype('float64')

In [16]:
mx_1s = np.ones((3,4)) # row, col
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
mx_0s = np.zeros((4,6), dtype= int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [19]:
mx_0s = np.zeros((3,4),dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [20]:
en_mx = np.empty((3,3)) # Make emtry matrix but ganarate random value
print(en_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.00783825e-321]
 [1.27319747e-313 1.54544953e-310 3.25134978e+294]]


In [21]:
# Video 10 Done

In [22]:
arr_1d = np.arange(1,13) #(star, Ende, Steps)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [25]:
np.linspace(1,5,4) # (range start, range end, 4step) every step on same defarance

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [26]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
arr_1d.reshape(2,6) # convart 1d array to 2d array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr_1d.reshape(2,3,2) # 1d to 3d array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [31]:
ar = np.arange(1,13).reshape(3,4)
print(ar)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
ar.ravel() # multidymanshon to 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
ar.flatten() # multidymanshon to 1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
ar.transpose() # make row into col

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [38]:
# video 11 done