In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1,2,3,4]) # Make 1D array
print(arr_1d)

[1 2 3 4]


In [4]:
type(arr_1d)

numpy.ndarray

In [5]:
arr_1d.ndim # To Chack array dymanshon

1

In [6]:
arr_2d = np.array([  # Make 2D array
    [1,2,3,4],
    [5,6,7,8] 
    ])

print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr_2d.ndim # To Chack array dymanshon

2

In [8]:
arr_2d.size # Chack array size

8

In [9]:
arr_1d.size # Check array size

4

In [10]:
arr_2d.shape # row, colm

(2, 4)

In [11]:
arr_2d.dtype # Check data type

dtype('int32')

In [12]:
# Video 09 Done ----->

In [13]:
mx_1s = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
mx_1s = np.ones(5) # Dymanshon of colam
print(mx_1s)

[1. 1. 1. 1. 1.]


In [16]:
mx_1s.dtype

dtype('float64')

In [17]:
mx_1s = np.ones((3,4)) # row, col
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
mx_0s = np.zeros((4,6), dtype= int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [21]:
mx_0s = np.zeros((3,4),dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [22]:
en_mx = np.empty((3,3)) # Make emtry matrix but ganarate random value
print(en_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.09478267e-321]
 [2.12199579e-313 7.66040481e-312 0.00000000e+000]]


In [23]:
# Video 10 Done