In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1,2,3,4]) # Make 1D array
print(arr_1d)

[1 2 3 4]


In [4]:
type(arr_1d)

numpy.ndarray

In [5]:
arr_1d.ndim # To Chack array dymanshon

1

In [6]:
arr_2d = np.array([  # Make 2D array
    [1,2,3,4],
    [5,6,7,8] 
    ])

print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr_2d.ndim # To Chack array dymanshon

2

In [8]:
arr_2d.size # Chack array size

8

In [9]:
arr_1d.size # Check array size

4

In [10]:
arr_2d.shape # row, colm

(2, 4)

In [11]:
arr_2d.dtype # Check data type

dtype('int32')

In [12]:
# Video 09 Done ----->

In [13]:
mx_1s = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
mx_1s = np.ones(5) # Dymanshon of colam
print(mx_1s)

[1. 1. 1. 1. 1.]


In [15]:
mx_1s.dtype

dtype('float64')

In [16]:
mx_1s = np.ones((3,4)) # row, col
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
mx_0s = np.zeros((4,6), dtype= int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [19]:
mx_0s = np.zeros((3,4),dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [20]:
en_mx = np.empty((3,3)) # Make emtry matrix but ganarate random value
print(en_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.00783825e-321]
 [1.27319747e-313 1.54544953e-310 3.25134978e+294]]


In [21]:
# Video 10 Done

In [22]:
arr_1d = np.arange(1,13) #(star, Ende, Steps)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [25]:
np.linspace(1,5,4) # (range start, range end, 4step) every step on same defarance

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [26]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
arr_1d.reshape(2,6) # convart 1d array to 2d array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr_1d.reshape(2,3,2) # 1d to 3d array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [31]:
ar = np.arange(1,13).reshape(3,4)
print(ar)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
ar.ravel() # multidymanshon to 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
ar.flatten() # multidymanshon to 1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
ar.transpose() # make row into col

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [39]:
ar.T # make row into col

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [38]:
# video 11 done

In [40]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
arr1 + arr2 # addishon tow array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [42]:
np.add(arr1,arr2) # addishon tow array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [43]:
arr1 - arr2 # Subtract tow array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
np.subtract(arr1, arr2) # Subtract tow array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [49]:
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [50]:
arr1 @ arr2 # First row first col multiply

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [51]:
arr1.dot(arr2) # First row first col multiply

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [52]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr1.max() # find maximam valu

9

In [56]:
arr1.argmax() # find index of max valu 

8

In [57]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr1.max(axis = 0) # 0 = col , 1 = row

array([7, 8, 9])

In [58]:
arr1.max(axis = 1) # 0 = col , 1 = row

array([3, 6, 9])

In [59]:
arr1.min() # find minimum valu

1

In [60]:
arr1.argmin() # find index of min valu 

0

In [61]:
arr1.min(axis = 0) # 0 = col , 1 = row

array([1, 2, 3])

In [62]:
np.sum(arr1) # total sum of array

45

In [63]:
np.sum(arr1, axis= 0) # sum of colom

array([12, 15, 18])

In [64]:
np.sum(arr1, axis= 1) # sum of row

array([ 6, 15, 24])

In [65]:
np.mean(arr1) # find avarage of array

5.0

In [66]:
np.sqrt(arr1) # find squre rute of array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [67]:
np.std(arr1) # find standard divishon

2.581988897471611

In [68]:
np.exp(arr1) # find exponent (e to the power x )

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [69]:
np.log(arr1) # find log of array

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [70]:
np.log10(arr1) # find value of log 1o of array

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [ ]:
# video 12 done